# Generated by Django 6.0.1 on 2026-03-13 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_customer_alter_category_options_and_more'),
        ('invents', '0002_category_location_rack_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.product'),
        ),
    ]
