# Generated by Django 6.0.1 on 2026-03-13 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_customer_alter_category_options_and_more'),
        ('invents', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
