# Generated by Django 6.0.1 on 2026-03-18 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invents', '0004_alter_stock_product_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rack',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
        migrations.AddField(
            model_name='rack',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='invents.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='invents.location'),
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('name', 'warehouse')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('name', 'location')},
        ),
    ]
