# Generated by Django 6.0.1 on 2026-03-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invents', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
