# Generated by Django 6.0.1 on 2026-03-28 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invents', '0007_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invents.rack'),
        ),
    ]
