# Generated by Django 6.0.1 on 2026-03-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_customer_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
