# Generated by Django 6.0.1 on 2026-03-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0004_supplier_alternate_phone_supplier_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
