# Generated by Django 6.0.1 on 2026-03-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0005_remove_product_minimum_stock_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
