# Generated by Django 6.0.1 on 2026-03-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0007_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
